
/**
 * My Home Dashboard App Module
 * 
 * Generated by Markus Wagner
 */

/**
 * Core Libraries and more
 */
/**
 * Angular Core Component Imports
 */
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Injectable } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { HttpModule } from '@angular/http';
import { FormsModule } from '@angular/forms';
/**
 * Additional Library Imports
 */
// import { DragulaModule } from 'ng2-dragula'; //TO BE DONE
import {SpotifyService} from 'angular2-spotify/angular2-spotify';

/**
 * Project based imports
 */
/**
 * Components
 */
import { AppComponent } from './app.component';
import { NavBarComponent } from './components/nav-bar/nav-bar.component';
import { CockpitComponent } from './pages/cockpit/cockpit.component';
import { ProjectsComponent } from './pages/projects/projects.component';
import { SoundExplorerComponent } from './pages/sound-explorer/sound-explorer.component';
import { TodosComponent } from './pages/todos/todos.component';

/**
 * Services
 */
import { TodosService } from './services/todos.service';
import { AuthService } from './services/auth.service';
import { SpotifyDataService } from './services/spotify-data.service';

/**
 * Pipes
 */
import { FilterPipe } from './pipes/filter.pipe';

const appRoutes: Routes = [
  {
    path: 'home',
    component: CockpitComponent
  },
  {
    path: 'projects',
    component: ProjectsComponent
  },
  {
    path: 'todos',
    component: TodosComponent
  },
  {
    path: 'sounds',
    component: SoundExplorerComponent
  },
  {
    path: '',
    redirectTo: '/home',
    pathMatch: 'full'
  },
  // { path: '**', component: PageNotFoundComponent }
];

@NgModule({
  declarations: [
    AppComponent,
    NavBarComponent,
    CockpitComponent,
    ProjectsComponent,
    SoundExplorerComponent,
    TodosComponent,
    FilterPipe
  ],
  imports: [
    RouterModule.forRoot(
      appRoutes,
      { useHash: true } //, enableTracing: true <-- debugging purposes only
    ),
    BrowserModule,
    HttpModule,
    FormsModule
  ],
  providers: [
    TodosService,
    AuthService,
    SpotifyService,
    SpotifyDataService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
